remote_theme: pages-themes/minimal@v0.2.0
title: 我的博客
description: 欢迎来到我的世界
lsi: false
safe: true
source: [/docs]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-spaceship